from asyncio import Event
from typing import Iterable, Protocol, TypeVar, TypeVarTuple

from ecs_framework.primitives import ComponentProtocol, DrawCommand, EntityId, ExecutionStage, Resource, SystemProtocol


R = TypeVar("R", bound=Resource)
Cs = TypeVarTuple("Cs")


class WorldProtocol(Protocol):

    def spawn(self, *components: ComponentProtocol) -> EntityId: ...

    def destroy(self, entity_id: EntityId) -> None: ...

    def add_component(self, entity_id: EntityId, component: ComponentProtocol) -> None: ...

    def remove_component(self, entity_id: EntityId, component_type: type[ComponentProtocol]) -> None: ...

    def remove_all(self, component_type: type[ComponentProtocol]) -> None: ...

    def query_entities(self,
                       all_of: tuple[type[ComponentProtocol], ...] = (),
                       any_of: tuple[type[ComponentProtocol], ...] = (),
                       none_of: tuple[type[ComponentProtocol], ...] = ()
     ) -> set[EntityId]:
        ...

    def query(self,
              *component_types: *Cs,
              all_of: tuple[type[ComponentProtocol], ...] = (),
              any_of: tuple[type[ComponentProtocol], ...] = (),
              none_of: tuple[type[ComponentProtocol], ...] = ()
     ) -> Iterable[tuple[EntityId, tuple[*Cs]]]:
        ...

    def register_temporary_component(self, component_type: type[ComponentProtocol]) -> None: ...

    def get_temporary_components(self) -> list[type[ComponentProtocol]]: ...
    
    def add_system(self, system: SystemProtocol, stage: ExecutionStage) -> None: ...

    def execute(self, delta_time: float) -> None: ...

    def set_resource(self, resource: Resource) -> None: ...

    def get_resource(self, resource: type[R]) -> R: ...

    def push_event(self, event: Event) -> None: ...

    def get_events(self) -> list[Event]: ...
    
    def clear_events(self) -> None: ...

    def add_draw_command(self, draw_command: DrawCommand) -> None: ...

    def get_draw_commands(self ) -> list[DrawCommand]: ...
    
    def clear_draw_commands(self) -> None: ...



class EntityManagerProtocol(Protocol): ...

class ComponentManagerProtocol(Protocol): ...

class SystemManagerProtocol(Protocol): ...

class ResourceManagerProtocol(Protocol): ...

class EventManagerProtocol(Protocol): ...

class RenderManagerProtocol(Protocol): ...
