from asyncio import Event
from typing import Iterable, Protocol, TypeVar, TypeVarTuple, runtime_checkable

from ecs_framework.primitives import ComponentProtocol, DrawCommand, EntityId, ExecutionStage, Resource, SystemProtocol


R = TypeVar("R", bound=Resource)
Cs = TypeVarTuple("Cs")


class WorldProtocol(Protocol):

    def spawn(self, *components: ComponentProtocol) -> EntityId: ...

    def destroy(self, entity_id: EntityId) -> None: ...

    def add_component(self, entity_id: EntityId, component: ComponentProtocol) -> None: ...

    def remove_component(self, entity_id: EntityId, component_type: type[ComponentProtocol]) -> None: ...

    def remove_all(self, component_type: type[ComponentProtocol]) -> None: ...

    def query_entities(self,
                       all_of: tuple[type[ComponentProtocol], ...] = (),
                       any_of: tuple[type[ComponentProtocol], ...] = (),
                       none_of: tuple[type[ComponentProtocol], ...] = ()
     ) -> set[EntityId]:
        ...

    def query(self,
              *component_types: *Cs,
              all_of: tuple[type[ComponentProtocol], ...] = (),
              any_of: tuple[type[ComponentProtocol], ...] = (),
              none_of: tuple[type[ComponentProtocol], ...] = ()
     ) -> Iterable[tuple[EntityId, tuple[*Cs]]]:
        ...

    def register_temporary_component(self, component_type: type[ComponentProtocol]) -> None: ...

    def get_temporary_components(self) -> list[type[ComponentProtocol]]: ...
    
    def add_system(self, system: SystemProtocol, stage: ExecutionStage) -> None: ...

    def execute(self, delta_time: float) -> None: ...

    def set_resource(self, resource: Resource) -> None: ...

    def get_resource(self, resource: type[R]) -> R: ...

    def push_event(self, event: Event) -> None: ...

    def get_events(self) -> list[Event]: ...
    
    def clear_events(self) -> None: ...

    def add_draw_command(self, draw_command: DrawCommand) -> None: ...

    def get_draw_commands(self ) -> list[DrawCommand]: ...
    
    def clear_draw_commands(self) -> None: ...


@runtime_checkable
class EntityManagerProtocol(Protocol): 

    def create(self) -> EntityId: ...
    
    def destroy(self, entity_id: EntityId) -> None: ...

    def exists(self, entity_id: EntityId) -> bool: ...

    def clear(self) -> None: ...


@runtime_checkable
class ComponentManagerProtocol(Protocol):

    def add(self, entity_id: EntityId, component: ComponentProtocol) -> None: ...

    def remove(self, entity_id: EntityId, component_type: type[ComponentProtocol]) -> None: ...

    def remove_all(self, component_type: type[ComponentProtocol]) -> None: ...

    def destroy(self, entity_id: EntityId) -> None: ...

    def has(self, entity_id: EntityId, component_type: type[ComponentProtocol]) -> bool: ...

    def query_entities(self,
                       all_of: tuple[type[ComponentProtocol], ...] = (),
                       any_of: tuple[type[ComponentProtocol], ...] = (),
                       none_of: tuple[type[ComponentProtocol], ...] = ()
     ) -> set[EntityId]:
        ...

    def query(self,
              *component_types: *Cs,
              all_of: tuple[type[ComponentProtocol], ...] = (),
              any_of: tuple[type[ComponentProtocol], ...] = (),
              none_of: tuple[type[ComponentProtocol], ...] = ()
     ) -> Iterable[tuple[EntityId, tuple[*Cs]]]:
        ...

    def register_temporary_component(self, component_type: type[ComponentProtocol]) -> None: ...

    def get_temporary_components(self) -> list[type[ComponentProtocol]]: ...

    def clear(self) -> None: ...


@runtime_checkable
class SystemManagerProtocol(Protocol):
   
    @property
    def all_systems(self) -> Iterable[SystemProtocol]: ...

    def add(self, system: SystemProtocol, stage: ExecutionStage) -> None: ...

    def remove(self, system_type: type[SystemProtocol]) -> None: ...

    def execute(self, delta_time: float) -> None: ...

    def clear(self) -> None: ...


@runtime_checkable
class ResourceManagerProtocol(Protocol): 
   
    def set(self, resource: Resource) -> None: ...

    def get(self, resource_type: type[R]) -> R | None: ...

    def remove(self, resource_type: type[Resource]) -> None: ...

    def clear(self) -> None: ...


@runtime_checkable
class EventManagerProtocol(Protocol): 

    def push(self, event: Event) -> None: ...

    def get(self) -> list[Event]: ...

    def clear(self) -> None: ...


@runtime_checkable
class RenderManagerProtocol(Protocol): 

    def push(self, command: DrawCommand) -> None: ...

    def get(self) -> list[DrawCommand]: ...

    def clear(self) -> None: ...
